name: Build Application

on:
  workflow_call:

jobs:
  build:
    name: Build ${{ matrix.component }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        component: [frontend, backend]
        include:
          - component: frontend
            path: ./frontend
            node-version: '22'
            build-command: npm run build
            artifact-path: frontend/dist/
          - component: backend
            path: ./backend
            node-version: '22'
            build-command: npm ci --production
            artifact-path: backend/
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ${{ matrix.path }}
        run: npm ci

      - name: Build application
        working-directory: ${{ matrix.path }}
        run: ${{ matrix.build-command }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: build-artifacts-${{ matrix.component }}
          path: ${{ matrix.artifact-path }}
          retention-days: 7
