name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      image-digest:
        description: "The digest of the container image to deploy"
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create Kubernetes manifests
        env:
          IMAGE_DIGEST: ${{ inputs.image-digest }}
        run: |
          mkdir -p k8s-deploy
          
          # Use the manifest from the repo but update the image
          if [ -f k8s/deployment.yaml ]; then
            sed "s|IMAGE_PLACEHOLDER|${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${IMAGE_DIGEST}|g" k8s/deployment.yaml > k8s-deploy/deployment.yaml
          fi
          
          echo "Kubernetes manifests prepared for deployment"
          ls -la k8s-deploy/ || true

      - name: Deploy to Kubernetes (Dry Run)
        run: |
          echo "🚀 Deployment Configuration Ready"
          echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ inputs.image-digest }}"
          echo ""
          echo "To complete deployment, configure kubectl with your cluster credentials"
          echo "and apply the manifests in k8s/ directory:"
          echo "  kubectl apply -f k8s/"
          echo ""
          echo "This workflow performs a dry-run. Configure KUBECONFIG secret for actual deployment."

      - name: Comment deployment info on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Deployment Ready**\n\nImage: \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ inputs.image-digest }}\`\n\n✅ All security checks passed\n✅ Image signed and verified`
            })
