name: SBOM Generation

on:
  workflow_call:

jobs:
  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          output-file: sbom.json
          upload-artifact: true

      - name: Upload SBOM
        uses: actions/upload-artifact@v5
        with:
          name: sbom
          path: sbom.json
          retention-days: 30
