name: SCA - Dependency Scanning

on:
  workflow_call:

jobs:
  sca-frontend:
    name: SCA - Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run npm audit
        id: npm-audit
        working-directory: ./frontend
        run: |
          npm audit --audit-level=moderate --json > audit-results.json || true
          cat audit-results.json

      - name: Scan dependencies with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scan-ref: './frontend'
          format: 'sarif'
          output: 'trivy-results-frontend.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results-frontend.sarif'

      - name: Show dependency tree for vulnerabilities
        if: always()
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scan-ref: './frontend'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Check for high severity vulnerabilities via npm audit
        id: check-vulns
        working-directory: ./frontend
        run: |
          npm audit --audit-level=high --json > audit-check.json || true
          HIGH_VULNS=$(jq '.metadata.vulnerabilities.high // 0' audit-check.json)
          CRITICAL_VULNS=$(jq '.metadata.vulnerabilities.critical // 0' audit-check.json)
          echo "high_vulns=$HIGH_VULNS" >> $GITHUB_OUTPUT
          echo "critical_vulns=$CRITICAL_VULNS" >> $GITHUB_OUTPUT
          
          echo "## Frontend Dependency Vulnerability Scan 
          🔓 Found $CRITICAL_VULNS critical and $HIGH_VULNS high severity vulnerabilities" >> $GITHUB_STEP_SUMMARY


      - name: Upload audit results
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: audit-results-frontend
          path: |
            frontend/audit-results.json
            frontend/audit-check.json

  sca-backend:
    name: SCA - Backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run npm audit
        id: npm-audit
        working-directory: ./backend
        run: |
          npm audit --audit-level=moderate --json > audit-results.json || true
          cat audit-results.json

      - name: Scan dependencies with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scan-ref: './backend'
          format: 'sarif'
          output: 'trivy-results-backend.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results-backend.sarif'

      - name: Show dependency tree for vulnerabilities
        if: always()
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scan-ref: './backend'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Check for high severity vulnerabilities via npm audit
        id: check-vulns
        working-directory: ./backend
        run: |
          npm audit --audit-level=high --json > audit-check.json || true
          HIGH_VULNS=$(jq '.metadata.vulnerabilities.high // 0' audit-check.json)
          CRITICAL_VULNS=$(jq '.metadata.vulnerabilities.critical // 0' audit-check.json)
          echo "high_vulns=$HIGH_VULNS" >> $GITHUB_OUTPUT
          echo "critical_vulns=$CRITICAL_VULNS" >> $GITHUB_OUTPUT
          
          echo "## Backend Dependency Vulnerability Scan 
          🔓 Found $CRITICAL_VULNS critical and $HIGH_VULNS high severity vulnerabilities" >> $GITHUB_STEP_SUMMARY


      - name: Upload audit results
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: audit-results-backend
          path: |
            backend/audit-results.json
            backend/audit-check.json
