name: Sign Container Image

on:
  workflow_call:
    inputs:
      image-digest:
        description: "The digest of the container image to sign"
        required: true
        type: string
    outputs:
      signature-verified:
        description: "Whether the signature was verified successfully"
        value: ${{ jobs.sign-image.outputs.signature-verified }}

env:
  REGISTRY: ghcr.io

jobs:
  sign-image:
    name: Sign Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      signature-verified: ${{ steps.verify.outputs.verified }}
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign container image
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_REF="${{ env.REGISTRY }}/${REPO_LOWER}@${{ inputs.image-digest }}"
          echo "Signing image: ${IMAGE_REF}"
          cosign sign --yes "${IMAGE_REF}"

      - name: Verify signature
        id: verify
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_REF="${{ env.REGISTRY }}/${REPO_LOWER}@${{ inputs.image-digest }}"
          echo "Verifying signature for: ${IMAGE_REF}"
          if cosign verify \
            --certificate-identity-regexp="https://github.com/${{ github.repository }}/*" \
            --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
            "${IMAGE_REF}"; then
            echo "verified=true" >> $GITHUB_OUTPUT
            echo "✅ Signature verified successfully"
          else
            echo "verified=false" >> $GITHUB_OUTPUT
            echo "❌ Signature verification failed"
            exit 1
          fi
